### ISSUE TITLE
Confirm Action

### ISSUE THREAD

**Issue by jrockefeller** [rickypc/robotframework-extendedselenium2library#10] opened 2016-03-20 20:43 UTC
Keyword Confirm Action fails to click on the action.
Can use Selenium2Library's Confirm Action and the keyword works properly

Happening on v.0.7.0+

**Comment by iradovanovic** [comment] 2016-03-22 10:25
+1

**Comment by rickypc** [comment] 2016-03-27 05:24
ES2L is using semi blocking page-ready check on keywords that internally called `Wait Until Angular Ready` keyword. There are two options to skip this behavior. The first can be done globally during library import by specifying `block_until_page_ready=${false}`. The second approach is using `skip_ready` argument on the `Click ?` - where `?` is any variant of clicks, ex: `Click Element`. This should give you exactly S2L behavior.

I take test cases for issue #3, which I believed talk about the same thing, and paste it below to show the differences between S2L and ES2L.

I will close this issue for now, please reopen if I didn't address your concern, and please elaborate further with specific steps to reproduce. Thanks.

```
*** Settings ***
Library  ExtendedSelenium2Library
Test Teardown  Close Browser

*** Test Cases ***
Test ES2L With Confirm Action
    Open Browser  file://${CURDIR}/../html/issue_3.html  ff                                                                                                                          
    Set Selenium Implicit Wait  0                                                                                                                                                    
    Choose Ok On Next Confirmation
    Click Link  Delete  skip_ready=${true}
    Confirm Action
    Page Should Contain  teapot

Test S2L With Confirm Action
    Import Library  Selenium2Library
    Set Library Search Order  Selenium2Library
    Open Browser  file://${CURDIR}/../html/issue_3.html  ff
    Choose Ok On Next Confirmation
    Click Link  Delete
    Confirm Action
    Page Should Contain  teapot
```

**Closed as completed by rickypc** 2016-03-27 05:24 UTC
Labels: question

**Comment by iradovanovic** [comment] 2016-03-30 15:21
Hi,
we still have some problem with "confirm action", actually the problem is following:

Error Msg:

> UnexpectedAlertPresentException: Alert Text: None
> Message: unexpected alert open: {Alert text : Are you sure?}

Part of code:

```
Delete Command Center
    [Arguments]                         ${commandCenterName}
    Open Command Center
    ${locator}                          Get Locator By Text            ${commandCenterName}
    Click Element                       ${locator}
    Wait Until Angular Ready            5
    Click Button                        ${commandCenterDeleteButton}
    Confirm Action
#    Alert Should Be Present
    Sleep                               1   Wait to finish action
```

But if we replace Confirm Action with  Alert Should Be Presented it will work.

robotframework==2.9.2
robotframework-extendedselenium2library==0.9.0

Last webdriver
Last chrome version.

**Comment by jrockefeller** [comment] 2016-03-30 15:53
I was able to resolve this by adding the skip_ready=${true} to the click button call
so your code would be:

Delete Command Center
    [Arguments]     ${commandCenterName}
    Open Command Center
    ${locator}    Get Locator By Text    ${commandCenterName}
    Click Element                       ${locator}
    Wait Until Angular Ready            5
    Click Button                        ${commandCenterDeleteButton}    skip_ready=${true}
    Confirm Action

# Alert Should Be Present

```
Sleep                               1   Wait to finish action
```

**Comment by iradovanovic** [comment] 2016-04-01 09:01
Yes, this is working. Tnx... but should be this solution ?

**Comment by iradovanovic** [comment] 2016-04-01 13:11
Ok, the problem is that now, I have to go through whole project (which is big) and change for each click before Confirm Action  -> skip_ready=${true}

**Comment by rickypc** [comment] 2016-04-02 04:21
Hi @iradovanovic,
ES2L would not know whether the click event would caused any confirm dialog or not, hence there is no way to be able to determine whether the library should skip the ready-check or not - without the flag.

I modified your example into two different approaches as below.

```
*** Settings ***
# Wait Until Angular Ready will use implicit_wait as its timeout value
Library    ExtendedSelenium2Library    implicit_wait=5

*** Keywords ***
Delete Command Center
    [Arguments]    ${commandCenterName}
    Open Command Center
    ${locator} =    Get Locator By Text    ${commandCenterName}
    # Wait Until Angular Ready will be called internally by Click Element
    Click Element    ${locator}
    Click Button    ${commandCenterDeleteButton}    skip_ready=${true}
    Confirm Action
    Sleep    1    Wait to finish action
```

```
*** Settings ***
# Wait Until Angular Ready will use implicit_wait as its timeout value
Library    ExtendedSelenium2Library    implicit_wait=5    block_until_page_ready=${false}

*** Keywords ***
Delete Command Center
    [Arguments]    ${commandCenterName}
    Open Command Center
    ${locator} =    Get Locator By Text    ${commandCenterName}
    # Wait Until Angular Ready will NOT be called internally by Click Element
    # because block_until_page_ready flag is set to ${false}
    Click Element    ${locator}
    # Only needed for AngularJS application
    Wait Until Angular Ready
    Click Button    ${commandCenterDeleteButton}
    Confirm Action
    Sleep    1    Wait to finish action
```

**Comment by iradovanovic** [comment] 2016-04-04 14:38
@rickypc
Aham.... tnx. The second example will probably fit more because we used "wait until angular ready" for a many cases and then block_until_page_ready=${false} will be the right thing. 
Tnx one more time!
